-- AlterTable
ALTER TABLE `product` MODIFY `stockStatus` ENUM('IN_STOCK', 'OUT_OF_STOCK', 'PREORDER', 'AVAILABLE', 'FINISHED') NOT NULL DEFAULT 'IN_STOCK';

-- AlterTable
ALTER TABLE `productvariant_size` MODIFY `stockStatus` ENUM('IN_STOCK', 'OUT_OF_STOCK', 'PREORDER', 'AVAILABLE', 'FINISHED') NOT NULL DEFAULT 'IN_STOCK';
