name: Azure Node.js Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Generate Prisma client
      - name: Generate Prisma client
        run: npx prisma generate 

      # Step 4b: Mark migration as resolved
      - name: Mark specific Prisma migration as resolved
        run: npx prisma migrate resolve --applied 20250902051217_added_pagesvisibility
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Step 4c: Run remaining Prisma migrations
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Step 5: Build TypeScript
      - name: Build TypeScript
        run: npm run build

      # Step 6: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: delivery-backend-ghana
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
